version: "3"
services:
  db:
    restart: always
    stdin_open: true
    tty: true
    image: postgres
    environment:
      POSTGRES_PASSWORD: simpsons1
      POSTGRES_USER: postgres
      POSTGRES_DB: user_pgdb
    ports:
    - 2345:5432
  db2:
    image: mongo:4.2
    container_name: db2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: Cluster0
      MONGO_INITDB_ROOT_USERNAME: rennanpo1
      MONGO_INITDB_ROOT_PASSWORD: simpsons1

  app:
    restart: always
    environment:
      DBPORT: 5432
    stdin_open: true
    tty: true
    image: my-node-app
    ports:
    - 13000:3000
    depends_on:
      - db